### ISSUE TITLE
how to write roi from np array

### ISSUE THREAD

**Issue by YubinXie** [hadim/read-roi#14]
If i generate a n-d array mask, any idea how to write into roi? Thanks!

**Comment by F-U-G-U-E** [comment]
Same question here! Is the problem solved now? If not, I think this will be helpful: 
[https://imagej.nih.gov/ij/developer/source/ij/io/RoiEncoder.java.html](url)

Sadly I am not so familiar with Java.

**Comment by hadim** [comment]
This package is only for reading ROI files generated by ImageJ. Writing is not implemented but PRs are welcome.
