### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hadim** [hadim/read-roi#22]
@scottclowe thanks for all the work.

I guess it makes sense to release a new version. Do you want to work one another PR?

If no then I'll wait for https://github.com/hadim/read-roi/pull/20 to be merged and release a new version.

**Comment by scottclowe** [comment]
> Do you want to work one another PR?

Not sure what you meant to say by this.

You could either do a new v1.5.3 release now with #19 and without #20, and then a v.1.6.0 with #20. Or just wait until #20 is merged and then do a v1.6.0 release without an intermediate v1.5.3.

**Comment by hadim** [comment]
I was just wondering if you wanted more time to work on other features but it looks like you're done :-)

So let's wait for #20 to be merged and I'll release 1.6.0.

**Comment by scottclowe** [comment]
Ah, I see! No, nothing more than what's currently up.

**Comment by hadim** [comment]
Thanks again!

https://pypi.org/project/read-roi/

(conda package will be live in a few hours)

**Comment by scottclowe** [comment]
Great, thanks! Having the support for composite ROIs in will be very helpful for me.

The things which I think could do with doing for the repo are to add tests for:
- [traced rois](https://codecov.io/gh/hadim/read-roi/src/master/read_roi/_read_roi.py#L437)
- [angle rois](https://codecov.io/gh/hadim/read-roi/src/master/read_roi/_read_roi.py#L445)
- [freeroi](https://codecov.io/gh/hadim/read-roi/src/master/read_roi/_read_roi.py#L449)s
- [sub pixel rectangles](https://codecov.io/gh/hadim/read-roi/src/master/read_roi/_read_roi.py#L357)
- [sub pixel ovals](https://codecov.io/gh/hadim/read-roi/src/master/read_roi/_read_roi.py#L369)
- running on [zip files](https://codecov.io/gh/hadim/read-roi/src/master/read_roi/_read_roi.py#L517)

And of course, to add the docstrings (#12).

BTW, I think you can close issues #6 and #7. :)

**Comment by hadim** [comment]
Feel free and I can also give you admin right on the repo if you want to (I don't really work on this lib anymore).

**Comment by scottclowe** [comment]
Yes, that might make things easier, thanks.
