### ISSUE TITLE
How can I save the rois into a zip file, which imageJ can open.

### ISSUE THREAD

**Issue by FengZhiheng** [hadim/read-roi#23]
Hi Hadrien. 
How can I save the rois into a zip file, which imageJ can open.
Thanks very much

**Comment by scottclowe** [comment]
Hi, Feng Zhiheng. Saving ROIs to a zip file for ImageJ to open is outside the scope of read-roi, which is just for reading ROIs which were exported from ImageJ into Python.

You could use [PymageJ](https://github.com/Jhsmit/PymageJ), but it can only write rectangular ROIs. Or use the [imagej](https://pypi.org/project/imagej/) package on pypi to interact with the ImageJ program from Python and tell it to save a ROI for you.

I don't know of an existing, fully-fledged Python implementation for writing to ImageJ ROIs. There is not much demand for one. If you want to develop one yourself, you could do so by referring to [RoiEncoder.java](https://imagej.nih.gov/ij/developer/source/ij/io/RoiEncoder.java.html) along with the source for PymageJ and read-roi which will illustrate how [RoiDecoder.java](http://rsb.info.nih.gov/ij/developer/source/ij/io/RoiDecoder.java.html) was mapped to a Python3 implementation.

**Comment by FengZhiheng** [comment]
I got it. It's very kind of you for your reply.



---Original---

**Comment by scottclowe** [comment]
No problem.

If you do find a Python implementation of an ImageJ-ROI exporter, or another solution that works for you (i.e. interfacing with ImageJ through the imagej package), please let us know so we can direct any one else who is looking for the same thing to your response.
