### ISSUE TITLE
unclosed ROIs are found 

### ISSUE THREAD

**Issue by YubinXie** [hadim/read-roi#6]
When I tried to recover the ROIs that I generated from the ImageJ, I found some of them are not closed. Example attached. The left is from ImageJ and the right is the one recovered using your codes. Appreciate if you can help this. 
![open_roi](https://user-images.githubusercontent.com/16257776/51096847-ad7d2c00-178d-11e9-9df3-90144de0af37.png)

**Comment by adamltyson** [comment]
I've also seen this (Loading `.zip` files with Python 3.6, Ubuntu 18.04 if that's relevant).

**Comment by scottclowe** [comment]
The data is loaded correctly from the ROI file, and so I think the current behaviour is the correct behaviour. If you want to close the path, just repeat the first node at the end of the list of nodes as @adamltyson mentions.

I think this issue can be marked as resolved.

**Comment by hadim** [comment]
Fixed!
